name: NPM Publish

on:
    workflow_dispatch:

jobs:
    build:
        name: build and pack
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"

            - name: npm install
              run: npm install

            - name: npm run build 🔧
              run: npm run build

            - name: npm pack 📦
              run: npm pack

            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                  name: archipelago-vue
                  path: pernod-ricard-archipelago-vue-*.*.*.tgz

    publish-npmjs_com:
        name: publish npmjs.com
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: package-manager-npmjs.com

        steps:
            - name: Download package from build job
              uses: actions/download-artifact@v2
              with:
                  name: archipelago-vue

            - name: Setup node and auth
              uses: actions/setup-node@v1
              with:
                  registry-url: "https://registry.npmjs.org"
                  always-auth: true

            - name: Publish package on NPM 📦
              run: npm publish pernod-ricard-archipelago-vue-*.*.*.tgz --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
